name = "novawing"
compatibility_date = "2026-06-14"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "novawing-leaderboard"
database_id = "efdd43e9-abc1-4992-9d4e-943be20ff579"
